=== tanishq2905/WAD-lab4/books.dtd
<!ELEMENT Books (Book+)>
<!ELEMENT Book (Title,Author,ISBN,Publisher,Edition,Price)>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT Author (#PCDATA)>
<!ELEMENT ISBN (#PCDATA)>
<!ELEMENT Publisher (#PCDATA)>
<!ELEMENT Edition (#PCDATA)>
<!ELEMENT Price (#PCDATA)>

=== tanishq2905/WAD-lab4/books.xml
<?xml version="1.0"?>

<!DOCTYPE Books SYSTEM "books.dtd">

<Books>

<Book>
<Title>XML Basics</Title>
<Author>John Smith</Author>
<ISBN>978123456789</ISBN>
<Publisher>TechPress</Publisher>
<Edition>2</Edition>
<Price>450</Price>
</Book>

<Book>
<Title>Web Technologies</Title>
<Author>David Miller</Author>
<ISBN>978987654321</ISBN>
<Publisher>Oxford</Publisher>
<Edition>3</Edition>
<Price>550</Price>
</Book>

</Books>
