=== tanishq2905/WAD-lab4/employees.dtd
<!ELEMENT Employees (Employee+)>
<!ELEMENT Employee (EmpID,EmpName,Department,Salary,Email)>
<!ELEMENT EmpID (#PCDATA)>
<!ELEMENT EmpName (#PCDATA)>
<!ELEMENT Department (#PCDATA)>
<!ELEMENT Salary (#PCDATA)>
<!ELEMENT Email (#PCDATA)>

=== tanishq2905/WAD-lab4/employees.xml
<?xml version="1.0"?>

<?xml-stylesheet type="text/css" href="employees.css"?>

<!DOCTYPE Employees SYSTEM "employees.dtd">

<Employees>

<Employee>
<EmpID>201</EmpID>
<EmpName>Raj</EmpName>
<Department>CSE</Department>
<Salary>50000</Salary>
<Email>raj@email.com</Email>
</Employee>

<Employee>
<EmpID>202</EmpID>
<EmpName>Priya</EmpName>
<Department>ECE</Department>
<Salary>55000</Salary>
<Email>priya@email.com</Email>
</Employee>

</Employees>
